"server only"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeroUIProvider } from "@heroui/system";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/header";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroUIProvider>
          <SessionProvider>
          <Suspense fallback={<div>Loading...</div>}>
          <Header />
          <div className="max-w-[1024px] mx-auto mt-5 px-6">
            {children}
          </div>
          </Suspense>
          </SessionProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
